# CC4

In [4]:
import numpy as np
import scipy as sp
import matplotlib as plt

## ACP

In [38]:
eignenvalues = np.array([3/2, 1/2]) * np.eye(2)
eigenvectors = np.array([[1., 1.], [1., -1]]) * 1 / np.sqrt(2)
eignenvalues, eigenvectors

(array([[1.5, 0. ],
        [0. , 0.5]]),
 array([[ 0.70710678,  0.70710678],
        [ 0.70710678, -0.70710678]]))

In [39]:
cov = eigenvectors @ eignenvalues @ eigenvectors.T
cov

array([[1. , 0.5],
       [0.5, 1. ]])

In [42]:
1.5/2.0

0.75

In [28]:
mu = np.array([0., 0., 0.])
cov = np.array([[1., 0., -0.1], [0., 1., 0.5], [-0.1, 0.5, 1.]])
cov

array([[ 1. ,  0. , -0.1],
       [ 0. ,  1. ,  0.5],
       [-0.1,  0.5,  1. ]])

In [25]:
eigenvalues, eigenvectors = np.linalg.eig(cov)

In [26]:
eigenvalues
i = np.argsort(eigenvalues)
eigenvalues[i]

array([0.49009805, 1.        , 1.50990195])

In [30]:
1 - np.sqrt(26/100), 1 + np.sqrt(26/100)

(np.float64(0.4900980486407215), np.float64(1.5099019513592786))

In [27]:
eigenvectors[:, i]

array([[-7.07106781e-01, -1.08866324e-16,  7.07106781e-01],
       [ 6.93375245e-01,  1.96116135e-01,  6.93375245e-01],
       [-1.38675049e-01,  9.80580676e-01, -1.38675049e-01]])

In [ ]:
U = np.array([[-0.5, 0., 0.5], [], []])